# .github/workflows/python_publish.yml

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write     # Required for PyPI Trusted Publishers
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy  # Optional: only if you use environment-specific settings

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI using Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
